name: validate-all-templates
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest 
    steps:
      - name: test
        shell: pwsh
        run: |
          Install-Module InvokeBuild
          Invoke-Build BuildBicep

  
  